### ISSUE TITLE
some pages cannot be opened

### ISSUE THREAD

**Issue by Sherlock-1** [madewithml/lessons#169]

**Comment by GokuMohandas** [comment]
hey @Sherlock-1, can you tell me which links are not opening?

**Comment by BackMountainDevil** [comment]
emm..I have another question.I just stat this rpo not watch. But I receive letters about this ussies .why??? When I read the three emails, I was wondering which web.....

**Comment by GokuMohandas** [comment]
@BackMountainDevil that's really weird that you're getting notifications for this. Go to Notifications (on the right side of the comment box) > Customize > Select `Not subscribed` -
Only receive notifications from this issue when you have participated or have been @mentioned.

**Comment by BackMountainDevil** [comment]
> @BackMountainDevil that's really weird that you're getting notifications for this. Go to Notifications (on the right side of the comment box) > Customize > Select `Not subscribed` -
> Only receive notifications from this issue when you have participated or have been @mentioned.
> 
> I'm going to close this issue in case it has some weird settings when Sherlock made it.

Thanks, bro. I am new here.

**Comment by Sherlock-1** [comment]
> 
> 
> hey @Sherlock-1, can you tell me which links are not opening?

the pages of "multilayer perceptrons" still cannot be opend.When i opened it,it showed 404.And its pages of colab was also wrong.
  the link of nootbook:  https://colab.research.google.com/github/madewithml/lessons/blob/master/notebooks/02_Basics/03_Multilayer_Perceptrons/03_TF_Multilayer_Perceptrons.ipynb
the link of github: https://github.com/madewithml/lessons/blob/master/notebooks/02_Basics/03_Multilayer_Perceptrons
